Schema.voices.Add("TGU", "moving", "Moving.", "grunt/advancing_on_target_01.wav")
Schema.voices.Add("TGU", "moving now", "Moving now.", "grunt/advancing_on_target_02.wav")
Schema.voices.Add("TGU", "pressing", "Pressing.", "grunt/advancing_on_target_03.wav")
Schema.voices.Add("TGU", "approaching target", "Approaching target.", "grunt/advancing_on_target_04.wav")
Schema.voices.Add("TGU", "pressure", "Pressure.", "grunt/advancing_on_target_05.wav")
Schema.voices.Add("TGU", "proceeding on infected", "Proceeding on infected.", "grunt/advancing_on_target_06.wav")
Schema.voices.Add("TGU", "forward steady", "Forward steady.", "grunt/advancing_on_target_07.wav")
Schema.voices.Add("TGU", "pushing forward", "Pushing forward.", "grunt/advancing_on_target_08.wav")
Schema.voices.Add("TGU", "moving on contaminant", "Moving on contaminant.", "grunt/advancing_on_target_10.wav")
Schema.voices.Add("TGU", "pressure on", "Pressure on.", "grunt/advancing_on_target_11.wav")
Schema.voices.Add("TGU", "echo one is forward pressure", "Echo-One is forward pressure.", "grunt/advancing_on_target_12.wav")
Schema.voices.Add("TGU", "closing on infected", "Closing on infected.", "grunt/advancing_on_target_13.wav")
Schema.voices.Add("TGU", "pushing", "Pushing.", "grunt/advancing_on_target_14.wav")
Schema.voices.Add("TGU", "echo one has sector id and is moving on infected", "Echo-One has Sector ID and is moving on infected.", "grunt/advancing_on_target_15.wav")
Schema.voices.Add("TGU", "pushing sector", "Pushing sector.", "grunt/advancing_on_target_16.wav")
Schema.voices.Add("TGU", "approaching contaminant", "Approaching contaminant.", "grunt/advancing_on_target_17.wav")
Schema.voices.Add("TGU", "going sharp", "Going sharp.", "grunt/announceattack_01.wav")
Schema.voices.Add("TGU", "engaging1", "Engaging.", "grunt/announceattack_02.wav")
Schema.voices.Add("TGU", "target engaged", "Target engaged.", "grunt/announceattack_03.wav")
Schema.voices.Add("TGU", "prosecuting", "Prosecuting.", "grunt/announceattack_04.wav")
Schema.voices.Add("TGU", "responding with full active", "Responding with full active.", "grunt/announceattack_05.wav")
Schema.voices.Add("TGU", "taking a shot", "Taking a shot.", "grunt/announceattack_06.wav")
Schema.voices.Add("TGU", "attacking with advantage", "Attacking with advantage.", "grunt/announceattack_07.wav")
Schema.voices.Add("TGU", "taking advantage", "Taking advantage.", "grunt/announceattack_08.wav")
Schema.voices.Add("TGU", "target locked daggers on", "Target locked, daggers on.", "grunt/announceattack_09.wav")
Schema.voices.Add("TGU", "weapons free", "Weapons free.", "grunt/announceattack_11.wav")
Schema.voices.Add("TGU", "target one in sightlines", "Target-One in sightlines.", "grunt/announceattack_alyx_01.wav")
Schema.voices.Add("TGU", "stop now", "Stop now.", "grunt/announceattack_alyx_02.wav")
Schema.voices.Add("TGU", "jackpot confirmed", "Jackpot confirmed.", "grunt/announceattack_alyx_03.wav")
Schema.voices.Add("TGU", "target one is life limited", "Target-One is life limited.", "grunt/announceattack_alyx_04.wav")
Schema.voices.Add("TGU", "i have her", "I have her.", "grunt/announceattack_alyx_05.wav")
Schema.voices.Add("TGU", "primary target echo one engage", "Primary target, Echo-One engage.", "grunt/announceattack_alyx_10.wav")
Schema.voices.Add("TGU", "breaking cover", "Breaking cover.", "grunt/announceattack_cover_01.wav")
Schema.voices.Add("TGU", "changing target code breakdown", "Changing target, Code: Breakdown.", "grunt/announceattack_cover_02.wav")
Schema.voices.Add("TGU", "designate target as shadow.", "Designate target as Shadow.", "grunt/announceattack_cover_03.wav")
Schema.voices.Add("TGU", "exposing hostile in 3", "Exposing hostile in 3...", "grunt/announceattack_cover_04.wav")
Schema.voices.Add("TGU", "target is protected rectifying", "Target is protected, rectifying.", "grunt/announceattack_cover_05.wav")
Schema.voices.Add("TGU", "echo one removing support", "Echo-One removing support.", "grunt/announceattack_cover_06.wav")
Schema.voices.Add("TGU", "echo one daggers on cover", "Echo-One, Daggers on cover.", "grunt/announceattack_cover_07.wav")
Schema.voices.Add("TGU", "full active on target cover", "Full active on target cover.", "grunt/announceattack_cover_08.wav")
Schema.voices.Add("TGU", "echo one going sharp on cover", "Echo-One going sharp on cover.", "grunt/announceattack_cover_09.wav")
Schema.voices.Add("TGU", "code breakdown", "Code Breakdown.", "grunt/announceattack_cover_10.wav")
Schema.voices.Add("TGU", "bouncer out", "Bouncer out.", "grunt/announceattack_grenade_01.wav")
Schema.voices.Add("TGU", "grenade out", "Grenade out.", "grunt/announceattack_grenade_02.wav")
Schema.voices.Add("TGU", "and extractor away", "And extractor away.", "grunt/announceattack_grenade_03.wav")
Schema.voices.Add("TGU", "bouncer bouncer", "Bouncer, bouncer.", "grunt/announceattack_grenade_04.wav")
Schema.voices.Add("TGU", "get down", "Get down!", "grunt/announceattack_grenade_05.wav")
Schema.voices.Add("TGU", "extractor in 3", "Extractor in 3...", "grunt/announceattack_grenade_06.wav")
Schema.voices.Add("TGU", "and extracting", "And extracting.", "grunt/announceattack_grenade_07.wav")
Schema.voices.Add("TGU", "deploying grenade", "Deploying grenade.", "grunt/announceattack_grenade_08.wav")
Schema.voices.Add("TGU", "standing back", "Standing back.", "grunt/announceattack_grenade_09.wav")
Schema.voices.Add("TGU", "bouncer free", "Bouncer free.", "grunt/announceattack_grenade_10.wav")
Schema.voices.Add("TGU", "antlion", "Antlion.", "grunt/announceenemy_antlion_01.wav")
Schema.voices.Add("TGU", "target antlion", "Target antlion.", "grunt/announceenemy_antlion_02.wav")
Schema.voices.Add("TGU", "contact antlion", "Contact, antlion.", "grunt/announceenemy_antlion_03.wav")
Schema.voices.Add("TGU", "antlion incoming", "Antlion incoming.", "grunt/announceenemy_antlion_04.wav")
Schema.voices.Add("TGU", "viscon antlion", "Viscon, antlion.", "grunt/announceenemy_antlion_06.wav")
Schema.voices.Add("TGU", "antlion echo one engaging", "Antlion, Echo-One engaging.", "grunt/announceenemy_antlion_07.wav")
Schema.voices.Add("TGU", "echo one contact antlion", "Echo-One contact, Antlion.", "grunt/announceenemy_antlion_08.wav")
Schema.voices.Add("TGU", "antlion here", "Antlion here.", "grunt/announceenemy_antlion_10.wav")
Schema.voices.Add("TGU", "parasitics", "Parasitics.", "grunt/announceenemy_headcrabs_01.wav")
Schema.voices.Add("TGU", "parasitics detected", "Parasitics detected.", "grunt/announceenemy_headcrabs_02.wav")
Schema.voices.Add("TGU", "ugh free parasitics inbound", "Ugh, free parasitics inbound.", "grunt/announceenemy_headcrabs_03.wav")
Schema.voices.Add("TGU", "echo one visual on parasitics", "Echo-One visual on parasitics.", "grunt/announceenemy_headcrabs_04.wav")
Schema.voices.Add("TGU", "contact parasitics", "Contact, parasitics.", "grunt/announceenemy_headcrabs_05.wav")
Schema.voices.Add("TGU", "i hate these things", "I hate these things.", "grunt/announceenemy_headcrabs_06.wav")
Schema.voices.Add("TGU", "we got parasitics over here", "We got parasitics over here.", "grunt/announceenemy_headcrabs_07.wav")
Schema.voices.Add("TGU", "light parasitics echo one", "Light parasitics, Echo-One.", "grunt/announceenemy_headcrabs_08.wav")
Schema.voices.Add("TGU", "parasitics here", "Parasitics here.", "grunt/announceenemy_headcrab_09.wav")
Schema.voices.Add("TGU", "parasitic infestation confirmed", "Parasitic infestation confirmed.", "grunt/announceenemy_headcrabs_10.wav")
Schema.voices.Add("TGU", "necrotics", "Necrotics.", "grunt/announceenemy_zombie_01.wav")
Schema.voices.Add("TGU", "necrotics inbound", "Necrotics inbound.", "grunt/announceenemy_zombie_02.wav")
Schema.voices.Add("TGU", "infestation alert", "Infestation alert.", "grunt/announceenemy_zombie_03.wav")
Schema.voices.Add("TGU", "echo one visual on necrotics", "Echo-One visual on necrotics.", "grunt/announceenemy_zombie_04.wav")
Schema.voices.Add("TGU", "contact necrotics", "Contact, necrotics.", "grunt/announceenemy_zombie_05.wav")
Schema.voices.Add("TGU", "i see necrotics", "I see necrotics.", "grunt/announceenemy_zombie_06.wav")
Schema.voices.Add("TGU", "we got necrotics", "We got necrotics.", "grunt/announceenemy_zombie_07.wav")
Schema.voices.Add("TGU", "necrotics active", "Necrotics active.", "grunt/announceenemy_zombie_08.wav")
Schema.voices.Add("TGU", "contact on necrotics", "Contact on necrotics.", "grunt/announceenemy_zombie_09.wav")
Schema.voices.Add("TGU", "necrotics here", "Necrotics here.", "grunt/announceenemy_zombie_10.wav")
Schema.voices.Add("TGU", "hostile down", "Hostile down.", "grunt/announcekill_01.wav")
Schema.voices.Add("TGU", "target down", "Target down.", "grunt/announcekill_02.wav")
Schema.voices.Add("TGU", "kill confirmed", "Kill confirmed.", "grunt/announcekill_03.wav")
Schema.voices.Add("TGU", "clean kill", "Clean kill.", "grunt/announcekill_04.wav")
Schema.voices.Add("TGU", "another one down", "Another one down.", "grunt/announcekill_05.wav")
Schema.voices.Add("TGU", "ended", "Ended.", "grunt/announcekill_06.wav")
Schema.voices.Add("TGU", "dead", "Dead.", "grunt/announcekill_07.wav")
Schema.voices.Add("TGU", "contact down", "grunt/announcekill_09.wav")
Schema.voices.Add("TGU", "theyre dead", "They're dead.", "grunt/announcekill_11.wav")
Schema.voices.Add("TGU", "echo one kill confirmed", "Echo-One kill confirmed.", "grunt/announcekill_12.wav")
Schema.voices.Add("TGU", "hostile neutralized", "Hostile neutralized.", "grunt/announcekill_13.wav")
Schema.voices.Add("TGU", "its done", "It's done.", "grunt/announcekill_14.wav")
Schema.voices.Add("TGU", "hostile is over", "Hostile is over.", "grunt/announcekill_15.wav")
Schema.voices.Add("TGU", "virome down", "Virome down.", "grunt/announcekill_antlion_01.wav")
Schema.voices.Add("TGU", "cleaned1", "Cleaned.", "grunt/announcekill_antlion_02.wav")
Schema.voices.Add("TGU", "target sterilized", "Target sterilized.", "grunt/announcekill_antlion_03.wav")
Schema.voices.Add("TGU", "cleansed", "Cleansed.", "grunt/announcekill_antlion_04.wav")
Schema.voices.Add("TGU", "parasitic contained", "Parasitic contained.", "grunt/announcekill_antlion_05.wav")
Schema.voices.Add("TGU", "cleaned2", "Cleaned.", "grunt/announcekill_headcrab_01.wav")
Schema.voices.Add("TGU", "sector clean1", "Sector clean.", "grunt/announcekill_headcrab_02.wav")
Schema.voices.Add("TGU", "thats one", "That's one.", "grunt/announcekill_headcrab_03.wav")
Schema.voices.Add("TGU", "contaminant contained", "Contaminant contained.", "grunt/announcekill_headcrab_04.wav")
Schema.voices.Add("TGU", "cleaned3", "Cleaned.", "grunt/announcekill_headcrab_05.wav")
Schema.voices.Add("TGU", "gross", "Gross.", "grunt/announcekill_headcrab_06.wav")
Schema.voices.Add("TGU", "outbreak ineffective", "Outbreak ineffective.", "grunt/announcekill_headcrab_07.wav")
Schema.voices.Add("TGU", "outbreak contained", "Outbreak contained.", "grunt/announcekill_headcrab_08.wav")
Schema.voices.Add("TGU", "one parasitic vacated", "One parasitic vacated.", "grunt/announcekill_headcrab_09.wav")
Schema.voices.Add("TGU", "high value target is contained", "High value target is contained.", "grunt/announcekill_player_01.wav")
Schema.voices.Add("TGU", "target one is quiet.", "Target-One is quiet.", "grunt/announcekill_player_02.wav")
Schema.voices.Add("TGU", "keep quiet", "Keep quiet.", "grunt/announcekill_player_03.wav")
Schema.voices.Add("TGU", "dead", "Dead.", "grunt/announcekill_player_07.wav")
Schema.voices.Add("TGU", "necro contained", "grunt/announcekill_zombie_01.wav")
Schema.voices.Add("TGU", "necrotic contained", "grunt/announcekill_zombie_02.wav")
Schema.voices.Add("TGU", "stay dead", "Stay dead.", "grunt/announcekill_zombie_03.wav")
Schema.voices.Add("TGU", "contaminant eliminated", "Contaminant eliminated.", "grunt/announcekill_zombie_04.wav")
Schema.voices.Add("TGU", "back to sleep", "Back to sleep.", "grunt/announcekill_zombie_05.wav")
Schema.voices.Add("TGU", "its dead", "It's dead.", "grunt/announcekill_zombie_06.wav")
Schema.voices.Add("TGU", "cleanse successful", "Cleanse successful.", "grunt/announcekill_zombie_07.wav")
Schema.voices.Add("TGU", "breathing1", "[Heavy Breathing]", "grunt/breathing_01.wav")
Schema.voices.Add("TGU", "breathing2", "[Exhausted Breathing]", "grunt/breathing_02.wav")
Schema.voices.Add("TGU", "breathing3", "[Painful Breathing]", "grunt/breathing_03.wav")
Schema.voices.Add("TGU", "breathing4", "[Hardly Breathing]", "grunt/breathing_04.wav")
Schema.voices.Add("TGU", "breathing5", "[Painfully Exhausted Breathing]", "grunt/breathing_05.wav")
Schema.voices.Add("TGU", "alpha", "Alpha.", "grunt/calloutcode_alpha_01.wav")
Schema.voices.Add("TGU", "and", "and", "grunt/calloutcode_and_01.wav")
Schema.voices.Add("TGU", "bravo", "Bravo.", "grunt/calloutcode_bravo_01.wav")
Schema.voices.Add("TGU", "charlie", "Charlie.", "grunt/calloutcode_charlie_01.wav")
Schema.voices.Add("TGU", "dash1", "Dash.", "grunt/calloutcode_dash_01.wav")
Schema.voices.Add("TGU", "delta", "Delta.", "grunt/calloutcode_delta_01.wav")
Schema.voices.Add("TGU", "echo1", "Echo.", "grunt/calloutcode_echo_01.wav")
Schema.voices.Add("TGU", "eight", "Eight.", "grunt/calloutcode_eight_01.wav")
Schema.voices.Add("TGU", "eleven", "Eleven.", "grunt/calloutcode_eleven_01.wav")
Schema.voices.Add("TGU", "fifty", "Fifty.", "grunt/calloutcode_fifty_01.wav")
Schema.voices.Add("TGU", "five", "Five.", "grunt/calloutcode_five_01.wav")
Schema.voices.Add("TGU", "fourty", "Fourty.", "grunt/calloutcode_forty_01.wav")
Schema.voices.Add("TGU", "four", "Four.", "grunt/calloutcode_four_01.wav")
Schema.voices.Add("TGU", "hundred", "Hundred.", "grunt/calloutcode_hundred_01.wav")
Schema.voices.Add("TGU", "niner", "Niner.", "grunt/calloutcode_niner_01.wav")
Schema.voices.Add("TGU", "null", "Null.", "grunt/calloutcode_null_01.wav")
Schema.voices.Add("TGU", "one", "One.", "grunt/calloutcode_one_01.wav")
Schema.voices.Add("TGU", "seven", "Seven.", "grunt/calloutcode_seven_01.wav")
Schema.voices.Add("TGU", "seventy", "Seventy.", "grunt/calloutcode_seventy_01.wav")
Schema.voices.Add("TGU", "six", "Six.", "grunt/calloutcode_six_01.wav")
Schema.voices.Add("TGU", "sixty", "Sixty.", "grunt/calloutcode_sixty_01.wav")
Schema.voices.Add("TGU", "ten", "Ten.", "grunt/calloutcode_ten_01.wav")
Schema.voices.Add("TGU", "thirty", "Thirty.", "grunt/calloutcode_thirty_01.wav")
Schema.voices.Add("TGU", "thousand", "Thousand.", "grunt/calloutcode_thousand_01.wav")
Schema.voices.Add("TGU", "three", "Three.", "grunt/calloutcode_three_01.wav")
Schema.voices.Add("TGU", "twelve", "Twelve.", "grunt/calloutcode_twelve_01.wav")
Schema.voices.Add("TGU", "twenty", "Twenty.", "grunt/calloutcode_twenty_01.wav")
Schema.voices.Add("TGU", "two", "Two.", "grunt/calloutcode_two_01.wav")
Schema.voices.Add("TGU", "anticitizens", "Anticitizens.", "grunt/calloutentity_anticitizens_01.wav")
Schema.voices.Add("TGU", "apf", "APF.", "grunt/calloutentity_apf_01.wav")
Schema.voices.Add("TGU", "aps", "APS.", "grunt/calloutentity_aps_01.wav")
Schema.voices.Add("TGU", "bladewall", "Bladewall.", "grunt/calloutentity_bladewall_01.wav")
Schema.voices.Add("TGU", "cowall", "Co-Wall.", "grunt/calloutentity_cowall_01.wav")
Schema.voices.Add("TGU", "echo one", "Echo-One.", "grunt/calloutentity_echoone_01.wav")
Schema.voices.Add("TGU", "friendly", "Friendly.", "grunt/calloutentity_friendly_01.wav")
Schema.voices.Add("TGU", "hammerwall", "Hammerwall.", "grunt/calloutentity_hammerwall_01.wav")
Schema.voices.Add("TGU", "hostiles", "Hostiles.", "grunt/calloutentity_hostiles_01.wav")
Schema.voices.Add("TGU", "free parasitics2", "Free parasitics.", "grunt/calloutentity_manyparasitics_01.wav")
Schema.voices.Add("TGU", "necrotic3", "Necrotic.", "grunt/calloutentity_necrotic_01.wav")
Schema.voices.Add("TGU", "overwatch1", "Overwatch.", "grunt/calloutentity_overwatch_01.wav")
Schema.voices.Add("TGU", "parasitic2", "Parasitic.", "grunt/calloutentity_parasitic_01.wav")
Schema.voices.Add("TGU", "wallhammer", "Wallhammer.", "grunt/calloutentity_wallhammer_01.wav")
Schema.voices.Add("TGU", "above", "Above.", "grunt/calloutlocation_above_01.wav")
Schema.voices.Add("TGU", "apartment", "Apartment.", "grunt/calloutlocation_apartment_01.wav")
Schema.voices.Add("TGU", "barrels", "Barrels.", "grunt/calloutlocation_barrells_01.wav")
Schema.voices.Add("TGU", "behind", "Behind.", "grunt/calloutlocation_behind_01.wav")
Schema.voices.Add("TGU", "below", "Below.", "grunt/calloutlocation_below_01.wav")
Schema.voices.Add("TGU", "bricks", "Bricks.", "grunt/calloutlocation_bricks_01.wav")
Schema.voices.Add("TGU", "bridge", "Bridge.", "grunt/calloutlocation_bridge_01.wav")
Schema.voices.Add("TGU", "building", "Building.", "grunt/calloutlocation_building_01.wav")
Schema.voices.Add("TGU", "car", "Car.", "grunt/calloutlocation_car_01.wav")
Schema.voices.Add("TGU", "crane", "Crane.", "grunt/calloutlocation_crane_01.wav")
Schema.voices.Add("TGU", "door", "Door.", "grunt/calloutlocation_door_01.wav")
Schema.voices.Add("TGU", "elevator", "Elevator.", "grunt/calloutlocation_elevator_01.wav")
Schema.voices.Add("TGU", "front", "Front.", "grunt/calloutlocation_front_01.wav")
Schema.voices.Add("TGU", "hut", "Hut.", "grunt/calloutlocation_hut_01.wav")
Schema.voices.Add("TGU", "pipes", "Pipes.", "grunt/calloutlocation_pipes_01.wav")
Schema.voices.Add("TGU", "shack", "Shack.", "grunt/calloutlocation_shack_01.wav")
Schema.voices.Add("TGU", "toilet", "Toilet.", "grunt/calloutlocation_toilet_01.wav")
Schema.voices.Add("TGU", "traincar", "Traincar.", "grunt/calloutlocation_traincar_01.wav")
Schema.voices.Add("TGU", "trash", "Trash.", "grunt/calloutlocation_trash_01.wav")
Schema.voices.Add("TGU", "truck", "Truck.", "grunt/calloutlocation_truck_01.wav")
Schema.voices.Add("TGU", "tunnel", "Tunnel.", "grunt/calloutlocation_tunnel_01.wav")
Schema.voices.Add("TGU", "van", "Van.", "grunt/calloutlocation_van_01.wav")
Schema.voices.Add("TGU", "wheels", "Wheels.", "grunt/calloutlocation_wheels_01.wav")
Schema.voices.Add("TGU", "woodpile", "Woodpile.", "grunt/calloutlocation_woodpile_01.wav")
Schema.voices.Add("TGU", "copy that echo one is sound on reporting all suspects", "Copy that.Echo-One is sound on and reporting all suspects.", "grunt/choreo_22_2002.wav")
Schema.voices.Add("TGU", "audible at sector alpha niner delta exposing hostile in 3", "Audible at sector: Alpha, Niner, Delta, Exposing hostile in 3.", "grunt/choreo_22_2003.wav")
Schema.voices.Add("TGU", "overwatch we have active hostiles advise preparations", "Overwatch we have active hostiles.Advise preparations.", "grunt/combat_idle_010.wav")
Schema.voices.Add("TGU", "overwatch we have active hostiles advise preparations2", "Overwatch we have active hostiles.Advise preparations.", "grunt/combat_idle_012.wav")
Schema.voices.Add("TGU", "negative target is still active", "Negative, Target is still active.", "grunt/combat_idle_020.wav")
Schema.voices.Add("TGU", "copy that forming condition alpha", "Copy that.Forming Condition: Alpha.", "grunt/combat_idle_030.wav")
Schema.voices.Add("TGU", "copy that forming condition alpha2", "Copy that.Forming Condition: Alpha at Grid Niner Dash Three Seven.", "grunt/combat_idle_032.wav")
Schema.voices.Add("TGU", "holding for advanced directive over", "Holding for advanced directive, over.", "grunt/combat_idle_040.wav")
Schema.voices.Add("TGU", "holding for advanced directive over2", "Holding for advanced directive, over.", "grunt/combat_idle_041.wav")
Schema.voices.Add("TGU", "confirmed recalibrating", "Confirmed, Re-calibrating.", "grunt/combat_idle_050.wav")
Schema.voices.Add("TGU", "confirmed recalibrating2", "Confirmed, Re-calibrating.", "grunt/combat_idle_051.wav")
Schema.voices.Add("TGU", "copy setting up position", "Copy, setting up position.", "grunt/combat_idle_060.wav")
Schema.voices.Add("TGU", "copy setting up position2", "grunt/combat_idle_061.wav")
Schema.voices.Add("TGU", "theyre still alive", "They're still alive.", "grunt/combat_idle_070.wav")
Schema.voices.Add("TGU", "theyre still alive2", "They're still alive.", "grunt/combat_idle_071.wav")
Schema.voices.Add("TGU", "copy that contain and control is underway", "Copy that, contain and control is underway.", "grunt/combat_idle_080.wav")
Schema.voices.Add("TGU", "copy that contain and control is underway2", "Copy that, contain and control is underway.", "grunt/combat_idle_081.wav")
Schema.voices.Add("TGU", "resolving", "Resolving.", "grunt/combat_idle_090.wav")
Schema.voices.Add("TGU", "10-4 negative on dagger renew locked and ready", "10-4, Negative on Dagger re-new.Locked and ready.", "grunt/combat_idle_100.wav")
Schema.voices.Add("TGU", "10-4 negative on dagger renew locked and ready2", "10-4, Negative on Dagger re-new.Locked and ready.", "grunt/combat_idle_101.wav")
Schema.voices.Add("TGU", "holding tactical advantage", "Holding tactical advantage.", "grunt/combat_idle_110.wav")
Schema.voices.Add("TGU", "holding tactical advantage2", "Holding tactical advantage.", "grunt/combat_idle_111.wav")
Schema.voices.Add("TGU", "still holding", "Still holding.", "grunt/combat_idle_120.wav")
Schema.voices.Add("TGU", "still holding2", "Still holding.", "grunt/combat_idle_121.wav")
Schema.voices.Add("TGU", "holding for biodat upload", "Holding for biodat upload.", "grunt/combat_idle_130.wav")
Schema.voices.Add("TGU", "preparing for sundown", "Preparing for sundown.", "grunt/combat_idle_140.wav")
Schema.voices.Add("TGU", "preparing for sundown2", "Preparing for sundown.", "grunt/combat_idle_141.wav")
Schema.voices.Add("TGU", "preparing comms for extended conflict", "Preparing comms for extended conflict.", "grunt/combat_idle_150.wav")
Schema.voices.Add("TGU", "preparing comms for extended conflict2", "Preparing comms for extended conflict.", "grunt/combat_idle_151.wav")
Schema.voices.Add("TGU", "negative no daggers needed", "Negative, No daggers needed.", "grunt/combat_idle_160.wav")
Schema.voices.Add("TGU", "extending conflict duration", "Extending conflict duration.", "grunt/combat_idle_171.wav")
Schema.voices.Add("TGU", "scanning hostile biodats", "Scanning hostile biodats.", "grunt/combat_idle_180.wav")
Schema.voices.Add("TGU", "disregarding last call", "Disregarding last call.", "grunt/combat_idle_190.wav")
Schema.voices.Add("TGU", "cover me", "Cover me.", "grunt/coverme_01.wav")
Schema.voices.Add("TGU", "cover1", "Cover.", "grunt/coverme_02.wav")
Schema.voices.Add("TGU", "echo one requesting cover", "Echo-One requesting cover.", "grunt/coverme_03.wav")
Schema.voices.Add("TGU", "need covering fire", "Need covering fire.", "grunt/coverme_04.wav")
Schema.voices.Add("TGU", "echo one requesting shadow", "Echo-One requesting shadow.", "grunt/coverme_05.wav")
Schema.voices.Add("TGU", "prepare stimdose", "Prepare stimdose.", "grunt/coverme_06.wav")
Schema.voices.Add("TGU", "requesting cover at", "Requesting cover at...", "grunt/coverme_07.wav")
Schema.voices.Add("TGU", "evading", "Evading.", "grunt/danger_grenade_01.wav")
Schema.voices.Add("TGU", "grenade1", "Grenade.", "grunt/danger_grenade_02.wav")
Schema.voices.Add("TGU", "taking cover", "Taking cover.", "grunt/danger_grenade_03.wav")
Schema.voices.Add("TGU", "live grenade", "Live grenade.", "grunt/danger_grenade_04.wav")
Schema.voices.Add("TGU", "possible extractor evading", "Possible extractor, evading.", "grunt/danger_grenade_05.wav")
Schema.voices.Add("TGU", "grenade move", "Grenade, move!", "grunt/danger_grenade_06.wav")
Schema.voices.Add("TGU", "go cover", "Go cover!", "grunt/danger_grenade_07.wav")
Schema.voices.Add("TGU", "audible bouncer at sector", "Audible bouncer at sector...", "grunt/danger_grenade_08.wav")
Schema.voices.Add("TGU", "get back", "Get back!", "grunt/danger_grenade_09.wav")
Schema.voices.Add("TGU", "light bouncer finding shade", "Light bouncer, finding shade.", "grunt/danger_grenade_10.wav")
Schema.voices.Add("TGU", "closing in", "Closing in.", "grunt/establishinglof_01.wav")
Schema.voices.Add("TGU", "echo one switching position", "Echo-One switching position.", "grunt/establishinglof_02.wav")
Schema.voices.Add("TGU", "fixing visuals", "Fixing visuals.", "grunt/establishinglof_03.wav")
Schema.voices.Add("TGU", "honing sightlines", "Honing sightlines.", "grunt/establishinglof_04.wav")
Schema.voices.Add("TGU", "realigning to hostile", "Re-aligning to hostile.", "grunt/establishinglof_05.wav")
Schema.voices.Add("TGU", "forming visual confirmation", "Forming visual confirmation.", "grunt/establishinglof_06.wav")
Schema.voices.Add("TGU", "echo one no visual on target moving", "Echo-One, no visual on target, moving.", "grunt/establishinglof_08.wav")
Schema.voices.Add("TGU", "realigning target delta", "Re-aligning target delta.", "grunt/establishinglof_09.wav")
Schema.voices.Add("TGU", "stay there", "Stay there.", "grunt/establishinglof_10.wav")
Schema.voices.Add("TGU", "changing position", "Changing position.", "grunt/establishinglof_11.wav")
Schema.voices.Add("TGU", "optimizing location", "Optimizing location.", "grunt/establishinglof_12.wav")
Schema.voices.Add("TGU", "amending sightlines on hostile", "Amending sightlines on hostile.", "grunt/establishinglof_13.wav")
Schema.voices.Add("TGU", "viscon interrupted moving", "Viscon interrupted, moving.", "grunt/establishinglof_14.wav")
Schema.voices.Add("TGU", "clearing sightlines", "Clearing sightlines.", "grunt/establishinglof_15.wav")
Schema.voices.Add("TGU", "contact in 3", "Contact in 3...", "grunt/establishinglof_17.wav")
Schema.voices.Add("TGU", "exposing primary", "Exposing primary.", "grunt/establishinglof_18.wav")
Schema.voices.Add("TGU", "dont move", "Don't move.", "grunt/establishinglof_19.wav")
Schema.voices.Add("TGU", "cease fire target is friendly", "Cease fire, target is friendly.", "grunt/fakeout_responseceasefire_01.wav")
Schema.voices.Add("TGU", "weapons down echo one weapons down", "Weapons down, Echo-One weapons down!", "grunt/fakeout_responseceasefire_02.wav")
Schema.voices.Add("TGU", "ceasing fire daggers down", "Ceasing fire, daggers down.", "grunt/fakeout_responseceasefire_03.wav")
Schema.voices.Add("TGU", "laugh", "Hahaha.", "grunt/fakeout_success_01.wav")
Schema.voices.Add("TGU", "haha friend game effective", "[Inner Chuckle], friend game effective.", "grunt/fakeout_success_02.wav")
Schema.voices.Add("TGU", "haha hostile scrambled", "[Inner Chuckle], hostile scrambled.", "grunt/fakeout_success_03.wav")
Schema.voices.Add("TGU", "firing", "Firing.", "grunt/firing_01.wav")
Schema.voices.Add("TGU", "engaging target", "Engaging target.", "grunt/firing_02.wav")
Schema.voices.Add("TGU", "open daggers on hostile.", "Open daggers on hostile.", "grunt/firing_03.wav")
Schema.voices.Add("TGU", "echo one at primary setpoint", "Echo-One at primary setpoint.", "grunt/firing_05.wav")
Schema.voices.Add("TGU", "open a pressure on hostile", "Open a pressure on hostile.", "grunt/firing_07.wav")
Schema.voices.Add("TGU", "cleaning sector", "Cleaning sector.", "grunt/firing_08.wav")
Schema.voices.Add("TGU", "ammended", "Ammended.", "grunt/firing_09.wav")
Schema.voices.Add("TGU", "prosecuting sector", "Prosecuting sector.", "grunt/firing_10.wav")
Schema.voices.Add("TGU", "echo one is engaged and firing", "Echo-One is engaged and firing.", "grunt/firing_110.wav")
Schema.voices.Add("TGU", "enforcing stability on primary target", "Enforcing stability on primary target.", "grunt/firing_121.wav")
Schema.voices.Add("TGU", "enforcing stability on primary target2", "Enforcing stability on primary target at Sector...", "grunt/firing_122.wav")
Schema.voices.Add("TGU", "target is in line and receiving spikes", "Target is in line and receiving spikes.", "grunt/firing_132.wav")
Schema.voices.Add("TGU", "escalating force on primary target", "Escalating force on primary target.", "grunt/firing_142.wav")
Schema.voices.Add("TGU", "theyre going down", "They're going down.", "grunt/firing_151.wav")
Schema.voices.Add("TGU", "theyre going down2", "They're going down.", "grunt/firing_152.wav")
Schema.voices.Add("TGU", "almost over", "Almost over.", "grunt/firing_160.wav")
Schema.voices.Add("TGU", "almost over2", "Its almost over.", "grunt/firing_161.wav")
Schema.voices.Add("TGU", "sending spikes", "Sending spikes.", "grunt/firing_171.wav")
Schema.voices.Add("TGU", "sending all spikes to primary target", "Sending all spikes to primary target.", "grunt/firing_180.wav")
Schema.voices.Add("TGU", "echo one sending all spikes", "Echo-One sending all spikes.", "grunt/firing_192.wav")
Schema.voices.Add("TGU", "dont resist", "Don't resist.", "grunt/firing_200.wav")
Schema.voices.Add("TGU", "dont resist2", "Don't resist!", "grunt/firing_201.wav")
Schema.voices.Add("TGU", "dont resist3", "Don't resist.", "grunt/firing_202.wav")
Schema.voices.Add("TGU", "wallhammer is engaged and firing", "Wallhammer is engaged and firing.", "grunt/firing_210.wav")
Schema.voices.Add("TGU", "wallhammer is engaged and firing2", "Wallhammer is engaged and firing.", "grunt/firing_211.wav")
Schema.voices.Add("TGU", "ordinal is engaged and firing", "Ordinal is engaged and firing.", "grunt/firing_220.wav")
Schema.voices.Add("TGU", "ordinal is engaged and firing2", "Ordinal is engaged and firing.", "grunt/firing_221.wav")
Schema.voices.Add("TGU", "ordinal is engaged and firing3", "Ordinal is engaged and firing.", "grunt/firing_222.wav")
Schema.voices.Add("TGU", "apf is engaged and firing", "APF is engaged and firing.", "grunt/firing_230.wav")
Schema.voices.Add("TGU", "apf is engaged and firing2", "APF is engaged and firing.", "grunt/firing_231.wav")
Schema.voices.Add("TGU", "apf is engaged and firing3", "APF is engaged and firing.", "grunt/firing_232.wav")
Schema.voices.Add("TGU", "opening fire at priority one", "Opening fire at priority one.", "grunt/firing_player_01.wav")
Schema.voices.Add("TGU", "opening fire at target one", "Opening fire at target one.", "grunt/firing_player_04.wav")
Schema.voices.Add("TGU", "animal is in the pit", "Animal is in the pit.", "grunt/firing_player_07.wav")
Schema.voices.Add("TGU", "jackpot confirmed firing", "Jackpot confirmed, firing.", "grunt/firing_player_08.wav")
Schema.voices.Add("TGU", "clearing last known", "Clearing last known.", "grunt/flushing_01.wav")
Schema.voices.Add("TGU", "distribution on 3", "Distribution on 3...", "grunt/flushing_02.wav")
Schema.voices.Add("TGU", "flushing sector", "Flushing sector.", "grunt/flushing_03.wav")
Schema.voices.Add("TGU", "extracting at last known", "Extracting at last known.", "grunt/flushing_04.wav")
Schema.voices.Add("TGU", "applying pressure on last known flare down", "Applying pressure on last known, flare down.", "grunt/flushing_05.wav")
Schema.voices.Add("TGU", "flushing hostile", "Flushing hostile.", "grunt/flushing_06.wav")
Schema.voices.Add("TGU", "bouncer bouncer on last known", "Bouncer bouncer on last known.", "grunt/flushing_07.wav")
Schema.voices.Add("TGU", "disposing", "Disposing.", "grunt/getback_01.wav")
Schema.voices.Add("TGU", "releasing", "Releasing.", "grunt/getback_05.wav")
Schema.voices.Add("TGU", "audible at sector", "Audible at sector.", "grunt/hear_suspicious_01.wav")
Schema.voices.Add("TGU", "possible contaminant", "Possible contaminant.", "grunt/hear_suspicious_02.wav")
Schema.voices.Add("TGU", "possible hostile active", "Possible hostile active.", "grunt/hear_suspicious_03.wav")
Schema.voices.Add("TGU", "movement", "Movement.", "grunt/hear_suspicious_04.wav")
Schema.voices.Add("TGU", "sound on", "Sound on.", "grunt/hear_suspicious_05.wav")
Schema.voices.Add("TGU", "echo one is sound on reporting all suspects", "Echo-One is sound on reporting all suspects.", "grunt/hear_suspicious_06.wav")
Schema.voices.Add("TGU", "uh yeah nothing to report over", "Uh, yeah, nothing to report, over.", "grunt/idle_01.wav")
Schema.voices.Add("TGU", "number game", "1, 14, 3, 6, 11, Check. All clear on Echo Four, Over.", "grunt/idle_02.wav")
Schema.voices.Add("TGU", "echo one has negative movement", "Echo-One has negative movement, Grid Seven Dash Two.", "grunt/idle_04.wav")
Schema.voices.Add("TGU", "idle1", "Clean, Affirmative. Echo-One reporting Low Mike, No sound. Standing by for opportunities.", "grunt/idle_05.wav")
Schema.voices.Add("TGU", "idle2", "Condition Clear. Negative on Condition: Quicksand. Uhh, wait. No. Radials clear, over.", "grunt/idle_06.wav")
Schema.voices.Add("TGU", "idle3", "Overwatch, this is Echo-Four, requesting proximity data on hostiles. Holding for transmission.", "grunt/idle_07.wav")
Schema.voices.Add("TGU", "idle4", "Sector is tracking at 43% stable aaand still holding for transmission, over.", "grunt/idle_08.wav")
Schema.voices.Add("TGU", "idle5", "Overwatch is confirming Sector Lockdown, Anti-Citizen One is uhh displaced and activated, Keep sightlines open and sound on.", "grunt/idle_09.wav")
Schema.voices.Add("TGU", "idle6", "Affirmative Outbreak Status is Code Delta Seven in Sundown is on contact overrun. Uhh, Copy that.", "grunt/idle_10.wav")
Schema.voices.Add("TGU", "idle7", "Negative, Copy that, No Sector Containment. No confirmation on Target One Vector. Waiting for secondary perimeter codes.", "grunt/idle_11.wav")
Schema.voices.Add("TGU", "idle8", "Updating biodat, Stimdose 32, Dagger 78, Shield 100, Byprox 73, Audibles 3, Lightvis 15, Echo Out.", "grunt/idle_12.wav")
Schema.voices.Add("TGU", "idle9", "Roger that. Setting viscerators in Apex 5, We have biotics at the perimeter. Uhh, waiting for contact. Over.", "grunt/idle_13.wav")
Schema.voices.Add("TGU", "nontagged viromes inbound", "Overwatch confirms uhh non-tagged viromes inbound, all units advisory prepare for contact.", "grunt/idle_14.wav")
Schema.voices.Add("TGU", "callout code", "Callout Code: Delta, Echo, Seven, Niner, Alpha: Two winder zero, Confirmed. Echo Out.", "grunt/idle_15.wav")
Schema.voices.Add("TGU", "copy accepted", "Updating cognitive suppression biodats, Update complete in T-Minus 3 seconds, dissonance resolved.", "grunt/idle_18.wav")
Schema.voices.Add("TGU", "memory resolvement", "Overwatch is requesting all units refresh and resolve, Cognitive Dissonance will not be tolerated, Negative. Memory is included, Update is live, acceptance is mandatory.", "grunt/idle_19.wav")
Schema.voices.Add("TGU", "idle10", "Stabilization Team holding position, Lightvis at 73, Audibles at 15, Overwatch confirms HVT is perimeter inbound. Stay alert.", "grunt/idle_20.wav")
Schema.voices.Add("TGU", "medic", "Medic!", "grunt/injured_01.wav")
Schema.voices.Add("TGU", "im hit requesting stimdose", "I'm hit, requesting stimdose.", "grunt/injured_02.wav")
Schema.voices.Add("TGU", "taking damage", "Taking damage.", "grunt/injured_03.wav")
Schema.voices.Add("TGU", "requesting additional bodypacks", "Requesting additional bodypacks.", "grunt/injured_04.wav")
Schema.voices.Add("TGU", "bodypacks holding", "Bodypacks holding.", "grunt/injured_05.wav")
Schema.voices.Add("TGU", "echo one is time limited", "Echo-One is time limited.", "grunt/injured_06.wav")
Schema.voices.Add("TGU", "laugh1", "[Chuckle]", "grunt/laugh_01.wav")
Schema.voices.Add("TGU", "laugh2", "[Louder Chuckle]", "grunt/laugh_02.wav")
Schema.voices.Add("TGU", "laugh3", "[Inner Chuckle]", "grunt/laugh_03.wav")
Schema.voices.Add("TGU", "laugh4", "[Louder Inner Chuckle]", "grunt/laugh_04.wav")
Schema.voices.Add("TGU", "laugh5", "[Loud Chuckle]", "grunt/laugh_05.wav")
Schema.voices.Add("TGU", "contaminant not visible", "Contaminant not visible.", "grunt/lostenemy_01.wav")
Schema.voices.Add("TGU", "god damn it", "God damn it.", "grunt/lostenemy_02.wav")
Schema.voices.Add("TGU", "echo one requesting location", "Echo-One requesting location.", "grunt/lostenemy_03.wav")
Schema.voices.Add("TGU", "target lost requesting location assist", "Target lost, requesting location assist.", "grunt/lostenemy_04.wav")
Schema.voices.Add("TGU", "location assist", "Location assist.", "grunt/lostenemy_05.wav")
Schema.voices.Add("TGU", "viscon negative on hostile", "Viscon negative on hostile.", "grunt/lostenemy_06.wav")
Schema.voices.Add("TGU", "lost sightlines on contaminant", "Lost sightlines on contaminant.", "grunt/lostenemy_07.wav")
Schema.voices.Add("TGU", "no visual responder", "No visual responder.", "grunt/lostenemy_08.wav")
Schema.voices.Add("TGU", "missing hostile sector unknown", "Missing hostile, sector unknown.", "grunt/lostvisual_01.wav")
Schema.voices.Add("TGU", "requesting hostile location", "Requesting hostile location.", "grunt/lostvisual_02.wav")
Schema.voices.Add("TGU", "requesting location", "Requesting location.", "grunt/lostvisual_03.wav")
Schema.voices.Add("TGU", "lost sight of hostile", "Lost sight of hostile.")
Schema.voices.Add("TGU", "location assist for echo one", "Location assist for Echo-One.", "grunt/lostvisual_05.wav")
Schema.voices.Add("TGU", "assist with location", "Assist with location.", "grunt/lostvisual_06.wav")
Schema.voices.Add("TGU", "need location assist on sector", "Need location assist on sector.", "grunt/lostvisual_07.wav")
Schema.voices.Add("TGU", "no visual overwatch assist", "No visual, Overwatch assist.", "grunt/lostvisual_08.wav")
Schema.voices.Add("TGU", "echo one is negative on visual", "Echo-One is negative on visual.", "grunt/lostvisual_09.wav")
Schema.voices.Add("TGU", "possible evasion requesting location", "Possible evasion, requesting location.", "grunt/lostvisual_10.wav")
Schema.voices.Add("TGU", "contaminant is quiet requesting last known sector", "Contaminant is quiet, requesting last known sector.", "grunt/lostvisual_player_01.wav")
Schema.voices.Add("TGU", "we have total visual blackout on target one", "We have total visual blackout on target one.", "grunt/lostvisual_player_02.wav")
Schema.voices.Add("TGU", "primary hostile is quiet", "Primary hostile is quiet.", "grunt/lostvisual_player_03.wav")
Schema.voices.Add("TGU", "checking cover", "Checking cover.", "grunt/lostvisual_player_05.wav")
Schema.voices.Add("TGU", "checking for target one", "Checking for target one.", "grunt/lostvisual_player_06.wav")
Schema.voices.Add("TGU", "viscon lost eyes on", "Viscon lost, eyes on.", "grunt/lostvisual_player_07.wav")
Schema.voices.Add("TGU", "all contact quiet requesting recon", "All contact quiet, requesting recon.", "grunt/lostvisual_player_08.wav")
Schema.voices.Add("TGU", "proximity", "Proximity!", "grunt/nearpanic_01.wav")
Schema.voices.Add("TGU", "proximity2", "Proximity.", "grunt/nearpanic_02.wav")
Schema.voices.Add("TGU", "stop", "Stoop!", "grunt/nearpanic_03.wav")
Schema.voices.Add("TGU", "assist assist assist", "Assist! Assist! Assist!", "grunt/nearpanic_04.wav")
Schema.voices.Add("TGU", "echo assist echo assist", "Echo assist, Echo assist!", "grunt/nearpanic_06.wav")
Schema.voices.Add("TGU", "back down back down", "Back down! Back Down!", "grunt/nearpanic_07.wav")
Schema.voices.Add("TGU", "wheels down recall echo seven recall echo seven", "Wheels down, Recall! Echo-Seven, Recall! Echo-Seven!", "grunt/nearpanic_08.wav")
Schema.voices.Add("TGU", "proximity alert on echo one respond assist", "Proximity alert on Echo-One, respond assist!", "grunt/nearpanic_09.wav")
Schema.voices.Add("TGU", "too close amending", "Too close, amending.", "grunt/nearpanic_10.wav")
Schema.voices.Add("TGU", "copy1", "Copy.", "grunt/orderresponse_positive_01.wav")
Schema.voices.Add("TGU", "roger", "Roger.", "grunt/orderresponse_positive_02.wav")
Schema.voices.Add("TGU", "copy that1", "Copy that.", "grunt/orderresponse_positive_03.wav")
Schema.voices.Add("TGU", "can do", "Can do.", "grunt/orderresponse_positive_04.wav")
Schema.voices.Add("TGU", "proceeding", "Proceeding.", "grunt/orderresponse_positive_05.wav")
Schema.voices.Add("TGU", "affirmative1", "Affirmative.", "grunt/orderresponse_positive_06.wav")	
Schema.voices.Add("TGU", "holding position", "Holding position.", "grunt/overwatch_01.wav")
Schema.voices.Add("TGU", "location locked", "Location locked.", "grunt/overwatch_02.wav")
Schema.voices.Add("TGU", "daggers ready", "Daggers ready.", "grunt/overwatch_03.wav")
Schema.voices.Add("TGU", "viscon on last known position", "Viscon on last known position.", "grunt/overwatch_04.wav")
Schema.voices.Add("TGU", "eyes on last known", "Eyes on last known.", "grunt/overwatch_05.wav")
Schema.voices.Add("TGU", "observing", "Observing.", "grunt/overwatch_06.wav")
Schema.voices.Add("TGU", "echo one is in position", "Echo-One is in position.", "grunt/overwatch_07.wav")
Schema.voices.Add("TGU", "holding focus", "Holding focus.", "grunt/overwatch_08.wav")
Schema.voices.Add("TGU", "stop sound stop sound", "Stop sound! Stop sound!", "grunt/overwatch_09.wav")
Schema.voices.Add("TGU", "hostile unwilling standby", "Hostile unwilling, standby.", "grunt/overwatch_10.wav")
Schema.voices.Add("TGU", "holding", "Holding.", "grunt/overwatch_11.wav")
Schema.voices.Add("TGU", "waiting for contact", "Waiting for contact.", "grunt/overwatch_12.wav")
Schema.voices.Add("TGU", "evaluating", "Evaluating.", "grunt/overwatch_13.wav")
Schema.voices.Add("TGU", "awaiting problem", "Awaiting problem.", "grunt/overwatch_14.wav")
Schema.voices.Add("TGU", "ready for containment", "Ready for containment.", "grunt/overwatch_15.wav")
Schema.voices.Add("TGU", "holding2", "Holding.", "grunt/overwatch_16.wav")
Schema.voices.Add("TGU", "eyes on", "Eyes on.", "grunt/overwatch_17.wav")
Schema.voices.Add("TGU", "and contaminant is locked", "Aand contaminant is locked.", "grunt/overwatch_18.wav")
Schema.voices.Add("TGU", "echo one securing edge", "Echo-One securing edge.", "grunt/overwatch_19.wav")
Schema.voices.Add("TGU", "checking all edges", "Checking all edges.", "grunt/overwatch_20.wav")

Schema.voices.Add("Combine", "0", "Zero.", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("Combine", "1", "One.", "npc/metropolice/vo/one.wav")
Schema.voices.Add("Combine", "10", "Ten.", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("Combine", "10-0 hunting", "10-0, 10-0, viscerator is hunting!", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
Schema.voices.Add("Combine", "100", "One-hundred.", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("Combine", "10-103 tag", "Possible 10-103, my location, alert TAG units.", "npc/metropolice/vo/possible10-103alerttagunits.wav")
Schema.voices.Add("Combine", "10-107", "I have a 10-107 here, send AirWatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
Schema.voices.Add("Combine", "10-108", "We have a 10-108!", "npc/metropolice/vo/wehavea10-108.wav")
Schema.voices.Add("Combine", "10-14", "Holding on 10-14 duty, eh, code four.", "npc/metropolice/vo/holdingon10-14duty.wav")
Schema.voices.Add("Combine", "10-15", "Prepare for 10-15.", "npc/metropolice/vo/preparefor1015.wav")
Schema.voices.Add("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("Combine", "10-25", "Any unit, report in with 10-25 as suspect.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
Schema.voices.Add("Combine", "10-30", "I have a 10-30, my 10-20, responding, code two.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav")
Schema.voices.Add("Combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
Schema.voices.Add("Combine", "10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav")
Schema.voices.Add("Combine", "10-78", "Dispatch, I need 10-78, officer in trouble!", "npc/metropolice/vo/dispatchIneed10-78.wav")
Schema.voices.Add("Combine", "10-8 standing by", "10-8, standing by.", "npc/metropolice/vo/ten8standingby.wav")
Schema.voices.Add("Combine", "10-8", "Unit is on-duty, 10-8.", "npc/metropolice/vo/unitisonduty10-8.wav")
Schema.voices.Add("Combine", "10-91d", "10-91d count is...", "npc/metropolice/vo/ten91dcountis.wav")
Schema.voices.Add("Combine", "10-97 goa", "10-97, that suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav")
Schema.voices.Add("Combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
Schema.voices.Add("Combine", "10-99", "Officer down, I am 10-99, I repeat, I am 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav")
Schema.voices.Add("Combine", "11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
Schema.voices.Add("Combine", "11-6", "Suspect 11-6, my 10-20 is...", "npc/metropolice/vo/suspect11-6my1020is.wav")
Schema.voices.Add("Combine", "11-99", "11-99, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
Schema.voices.Add("Combine", "2", "Two.", "npc/metropolice/vo/two.wav")
Schema.voices.Add("Combine", "20", "Twenty.", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("Combine", "200", "Two-hundred.", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("Combine", "3", "Three.", "npc/metropolice/vo/three.wav")
Schema.voices.Add("Combine", "30", "Thirty.", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("Combine", "300", "Three-hundred.", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("Combine", "34s at", "All units, BOL, we have 34-S at...", "npc/metropolice/vo/allunitsbol34sat.wav")
Schema.voices.Add("Combine", "4", "Four.", "npc/metropolice/vo/four.wav")
Schema.voices.Add("Combine", "40", "Fourty.", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("Combine", "404", "404 zone.", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("Combine", "408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav")
Schema.voices.Add("Combine", "415b", "Is 415b.", "npc/metropolice/vo/is415b.wav")
Schema.voices.Add("Combine", "5", "Five.", "npc/metropolice/vo/five.wav")
Schema.voices.Add("Combine", "50", "Fifty.", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("Combine", "505", "Dispatch, we need AirWatch, subject is 505!", "npc/metropolice/vo/airwatchsubjectis505.wav")
Schema.voices.Add("Combine", "6", "Six.", "npc/metropolice/vo/six.wav")
Schema.voices.Add("Combine", "60", "Sixty.", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("Combine", "603", "603, unlawful entry.", "npc/metropolice/vo/unlawfulentry603.wav")
Schema.voices.Add("Combine", "63", "63, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav")
Schema.voices.Add("Combine", "7", "Seven.", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("Combine", "70", "Seventy.", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("Combine", "8", "Eight.", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("Combine", "80", "Eighty.", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("Combine", "9", "Nine.", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("Combine", "90", "Ninety.", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("Combine", "that's a grenade", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav")
Schema.voices.Add("Combine", "acquiring", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav")
Schema.voices.Add("Combine", "administer", "Administer.", "npc/metropolice/vo/administer.wav")
Schema.voices.Add("Combine", "confirmed adw", "Confirmed as ADW on that suspect, 10-0.", "npc/metropolice/vo/confirmadw.wav")
Schema.voices.Add("Combine", "affirmative", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("Combine", "all units move", "All units, move in!", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("Combine", "amputate", "Amputate.", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("Combine", "anticitizen", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("Combine", "antiseptic", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav")
Schema.voices.Add("Combine", "apex", "Apex.", "npc/combine_soldier/vo/apex.wav")
Schema.voices.Add("Combine", "apply", "Apply.", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("Combine", "arrest positions", "All units, move to arrest positions!", "npc/metropolice/vo/movetoarrestpositions.wav")
Schema.voices.Add("Combine", "at checkpoint", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
Schema.voices.Add("Combine", "at location report", "Protection-teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav")
Schema.voices.Add("Combine", "back me up", "Back me up, I'm out!", "npc/metropolice/vo/backmeupImout.wav")
Schema.voices.Add("Combine", "backup", "Backup!", "npc/metropolice/vo/backup.wav")
Schema.voices.Add("Combine", "blade", "Blade.", "npc/combine_soldier/vo/blade.wav")
Schema.voices.Add("Combine", "bleeding", "Suspect is bleeding from multiple wounds!", "npc/metropolice/vo/suspectisbleeding.wav")
Schema.voices.Add("Combine", "blip", "Catch that blip on the stabilization readout?", "npc/metropolice/vo/catchthatbliponstabilization.wav")
Schema.voices.Add("Combine", "block holding", "Block is holding, cohesive.", "npc/metropolice/vo/blockisholdingcohesive.wav")
Schema.voices.Add("Combine", "block", "Block!", "npc/metropolice/vo/block.wav")
Schema.voices.Add("Combine", "bol 243", "CP, we need AirWatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav")
Schema.voices.Add("Combine", "boomer", "Boomer.", "npc/combine_soldier/vo/boomer.wav")
Schema.voices.Add("Combine", "break cover", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("Combine", "can1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav")
Schema.voices.Add("Combine", "can2", "Pick up the can!", "npc/metropolice/vo/pickupthecan2.wav")
Schema.voices.Add("Combine", "can3", "I said, pick up the can!", "npc/metropolice/vo/pickupthecan3.wav")
Schema.voices.Add("Combine", "can4", "Now, put it in the trash-can.", "npc/metropolice/vo/putitinthetrash1.wav")
Schema.voices.Add("Combine", "can5", "I said, put it in the trash-can!", "npc/metropolice/vo/putitinthetrash2.wav")
Schema.voices.Add("Combine", "can6", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav")
Schema.voices.Add("Combine", "canal", "Canal.", "npc/metropolice/vo/canal.wav")
Schema.voices.Add("Combine", "canalblock", "Canalblock!", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("Combine", "cauterize", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("Combine", "check miscount", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("Combine", "checkpoints", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav")
Schema.voices.Add("Combine", "citizen summoned", "Reporting citizen summoned into voluntary conscription for channel open service detail T94-332.", "npc/metropolice/vo/citizensummoned.wav")
Schema.voices.Add("Combine", "citizen", "Citizen.", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("Combine", "classify db", "Classify subject name as 'DB'; this block ready for clean-out.", "npc/metropolice/vo/classifyasdbthisblockready.wav")
Schema.voices.Add("Combine", "cleaned", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav")
Schema.voices.Add("Combine", "clear code 100", "Clear and code one-hundred.", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("Combine", "close on suspect", "All units, close on suspect!", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("Combine", "closing", "Closing!", {"npc/combine_soldier/vo/closing.wav", "npc/combine_soldier/vo/closing2.wav"})
Schema.voices.Add("Combine", "code 100", "Code one-hundred.", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("Combine", "code 2", "All units, code two!", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("Combine", "code 3", "Officer down, request all units, code three to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
Schema.voices.Add("Combine", "code 7", "Code seven.", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("Combine", "condemned", "Condemned zone!", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("Combine", "contact 243", "Contact with 243 suspect, my 10-20 is...", "npc/metropolice/vo/contactwith243suspect.wav")
Schema.voices.Add("Combine", "contact priority", "I have contact with a priority two!", "npc/metropolice/vo/contactwithpriority2.wav")
Schema.voices.Add("Combine", "contact", "Contact!", "npc/combine_soldier/vo/contact.wav")
Schema.voices.Add("Combine", "contained", "Contained.", "npc/combine_soldier/vo/contained.wav")
Schema.voices.Add("Combine", "control 100", "Control is one-hundred percent this location, no sign of that 647-E.", "npc/metropolice/vo/control100percent.wav")
Schema.voices.Add("Combine", "controlsection", "Control-section!", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("Combine", "converging", "Converging.", "npc/metropolice/vo/converging.wav")
Schema.voices.Add("Combine", "copy that", "Copy that.", "npc/combine_soldier/vo/copythat.wav")
Schema.voices.Add("Combine", "copy", "Copy.", "npc/metropolice/vo/copy.wav")
Schema.voices.Add("Combine", "cover", "Cover!", "npc/combine_soldier/vo/coverhurt.wav")
Schema.voices.Add("Combine", "cp compromised", "CP is compromised, re-establish!", "npc/metropolice/vo/cpiscompromised.wav")
Schema.voices.Add("Combine", "cp establish", "CP, we need to establish our perimeter at...", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
Schema.voices.Add("Combine", "cp overrun", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
Schema.voices.Add("Combine", "dagger", "Dagger.", "npc/combine_soldier/vo/dagger.wav")
Schema.voices.Add("Combine", "dash", "Dash.", "npc/combine_soldier/vo/dash.wav")
Schema.voices.Add("Combine", "db count", "DB count is...", "npc/metropolice/vo/dbcountis.wav")
Schema.voices.Add("Combine", "defender", "Defender!", "npc/metropolice/vo/defender.wav")
Schema.voices.Add("Combine", "deserviced area", "Deserviced area.", "npc/metropolice/vo/deservicedarea.wav")
Schema.voices.Add("Combine", "designate suspect", "Designate suspect as...", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("Combine", "destroy cover", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("Combine", "dislocate interpose", "Fire to dislocate that interpose!", "npc/metropolice/vo/firetodislocateinterpose.wav")
Schema.voices.Add("Combine", "dismounting hardpoint", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
Schema.voices.Add("Combine", "disp apb", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav")
Schema.voices.Add("Combine", "distribution block", "Distribution block.", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("Combine", "document", "Document.", "npc/metropolice/vo/document.wav")
Schema.voices.Add("Combine", "dont move", "Don't move!", "npc/metropolice/vo/dontmove.wav")
Schema.voices.Add("Combine", "echo", "Echo.", "npc/combine_soldier/vo/echo.wav")
Schema.voices.Add("Combine", "engaging", "Engaging!", "npc/combine_soldier/vo/engaging.wav")
Schema.voices.Add("Combine", "establish new cp", "Fall down, establish a new CP!", "npc/metropolice/vo/establishnewcp.wav")
Schema.voices.Add("Combine", "expose target", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
Schema.voices.Add("Combine", "external", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav")
Schema.voices.Add("Combine", "final verdict", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
Schema.voices.Add("Combine", "final warning", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
Schema.voices.Add("Combine", "first warning", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
Schema.voices.Add("Combine", "fist", "Fist.", "npc/combine_soldier/vo/fist.wav")
Schema.voices.Add("Combine", "flash", "Flash.", "npc/combine_soldier/vo/flash.wav")
Schema.voices.Add("Combine", "flatline", "Flatline.", "npc/combine_soldier/vo/flatline.wav")
Schema.voices.Add("Combine", "flush", "Flush.", "npc/combine_soldier/vo/flush.wav")
Schema.voices.Add("Combine", "free necrotics", "I have free necrotics!", "npc/metropolice/vo/freenecrotics.wav")
Schema.voices.Add("Combine", "get down", "Get down!", "npc/metropolice/vo/getdown.wav")
Schema.voices.Add("Combine", "get out", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav")
Schema.voices.Add("Combine", "getting 647e", "Still getting that 647-E from local surveillance.", "npc/metropolice/vo/stillgetting647e.wav")
Schema.voices.Add("Combine", "ghost", "Ghost.", "npc/combine_soldier/vo/ghost.wav")
Schema.voices.Add("Combine", "go again", "PT, go again.", "npc/metropolice/vo/ptgoagain.wav")
Schema.voices.Add("Combine", "go sharp", "Go sharp!", "npc/combine_soldier/vo/gosharp.wav")
Schema.voices.Add("Combine", "going in", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav")
Schema.voices.Add("Combine", "got a db", "Uh, we got a DB here, cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
Schema.voices.Add("Combine", "got him again", "Got him again, suspect is 10-20 at...", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
Schema.voices.Add("Combine", "got one accomplice", "I got one accomplice here!", "npc/metropolice/vo/gotoneaccomplicehere.wav")
Schema.voices.Add("Combine", "got suspect one", "I got suspect one here!", "npc/metropolice/vo/gotsuspect1here.wav")
Schema.voices.Add("Combine", "grenade", "Grenade!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("Combine", "grid", "Grid.", "npc/combine_soldier/vo/grid.wav")
Schema.voices.Add("Combine", "haha", "Haha.", "npc/metropolice/vo/chuckle.wav")
Schema.voices.Add("Combine", "hammer", "Hammer.", "npc/combine_soldier/vo/hammer.wav")
Schema.voices.Add("Combine", "hardpoint prosecute", "Is at hardpoint, ready to prosecute!", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
Schema.voices.Add("Combine", "hardpoint scanning", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav")
Schema.voices.Add("Combine", "helix", "Helix.", "npc/combine_soldier/vo/helix.wav")
Schema.voices.Add("Combine", "help", "Help!", "npc/metropolice/vo/help.wav")
Schema.voices.Add("Combine", "hero", "Hero!", "npc/metropolice/vo/hero.wav")
Schema.voices.Add("Combine", "hes 148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav")
Schema.voices.Add("Combine", "high priority", "High-priority region.", "npc/metropolice/vo/highpriorityregion.wav")
Schema.voices.Add("Combine", "hold it", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
Schema.voices.Add("Combine", "hold position", "Protection-team, hold this position.", "npc/metropolice/vo/holdthisposition.wav")
Schema.voices.Add("Combine", "hold", "Hold it!", "npc/metropolice/vo/holdit.wav")
Schema.voices.Add("Combine", "hunter", "Hunter.", "npc/combine_soldier/vo/hunter.wav")
Schema.voices.Add("Combine", "hurricane", "Hurricane.", "npc/combine_soldier/vo/hurricane.wav")
Schema.voices.Add("Combine", "i said move", "I said move along.", "npc/metropolice/vo/Isaidmovealong.wav")
Schema.voices.Add("Combine", "ice", "Ice.", "npc/combine_soldier/vo/ice.wav")
Schema.voices.Add("Combine", "in position", "In position.", "npc/metropolice/vo/inposition.wav")
Schema.voices.Add("Combine", "inbound", "Inbound.", "npc/combine_soldier/vo/inbound.wav")
Schema.voices.Add("Combine", "infected", "Infected.", "npc/combine_soldier/vo/infected.wav")
Schema.voices.Add("Combine", "infection", "Infection!", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("Combine", "infested", "Infested zone.", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("Combine", "inject", "Inject!", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("Combine", "inoculate", "Inoculate.", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("Combine", "intercede", "Intercede!", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("Combine", "interlock", "Interlock!", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("Combine", "investigate", "Investigate.", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("Combine", "investigating", "Investigating 10-103.", "npc/metropolice/vo/investigating10-103.wav")
Schema.voices.Add("Combine", "ion", "Ion.", "npc/combine_soldier/vo/ion.wav")
Schema.voices.Add("Combine", "is 10-108", "Is 10-108!", "npc/metropolice/vo/is10-108.wav")
Schema.voices.Add("Combine", "is 10-8", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav")
Schema.voices.Add("Combine", "is closing", "Is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav")
Schema.voices.Add("Combine", "is down", "Is down!", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("Combine", "is inbound", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav")
Schema.voices.Add("Combine", "is moving in", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav")
Schema.voices.Add("Combine", "is moving", "Is moving in!", "npc/metropolice/vo/ismovingin.wav")
Schema.voices.Add("Combine", "is passive", "Is passive.", "npc/metropolice/vo/ispassive.wav")
Schema.voices.Add("Combine", "is ready to go", "Is ready to go!", "npc/metropolice/vo/isreadytogo.wav")
Schema.voices.Add("Combine", "isolate", "Isolate!", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("Combine", "jet", "Jet.", "npc/combine_soldier/vo/jet.wav")
Schema.voices.Add("Combine", "judge", "Judge.", "npc/combine_soldier/vo/judge.wav")
Schema.voices.Add("Combine", "judgment", "Suspect, prepare to receive civil judgment!", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("Combine", "jurisdiction", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
Schema.voices.Add("Combine", "jury", "Jury!", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("Combine", "keep moving", "Keep moving!", "npc/metropolice/vo/keepmoving.wav")
Schema.voices.Add("Combine", "kilo", "Kilo.", "npc/combine_soldier/vo/kilo.wav")
Schema.voices.Add("Combine", "king", "King!", "npc/metropolice/vo/king.wav")
Schema.voices.Add("Combine", "last seen at", "Hiding, last seen at range...", "npc/metropolice/vo/hidinglastseenatrange.wav")
Schema.voices.Add("Combine", "leader", "Leader.", "npc/combine_soldier/vo/leader.wav")
Schema.voices.Add("Combine", "level 3", "I have a level three civil-privacy violator here!", "npc/metropolice/vo/level3civilprivacyviolator.wav")
Schema.voices.Add("Combine", "line", "Line!", "npc/metropolice/vo/line.wav")
Schema.voices.Add("Combine", "location", "Location?", "npc/metropolice/vo/location.wav")
Schema.voices.Add("Combine", "lock position", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav")
Schema.voices.Add("Combine", "lock", "Lock!", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("Combine", "look out", "Look out!", "npc/metropolice/vo/lookout.wav")
Schema.voices.Add("Combine", "loose parasitics", "Loose parasitics!", "npc/metropolice/vo/looseparasitics.wav")
Schema.voices.Add("Combine", "lost contact", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav")
Schema.voices.Add("Combine", "low on", "Running low on verdicts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav")
Schema.voices.Add("Combine", "mace", "Mace.", "npc/combine_soldier/vo/mace.wav")
Schema.voices.Add("Combine", "maintain cp", "All units, maintain this CP!", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("Combine", "malcompliance", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
Schema.voices.Add("Combine", "malcompliant 10-107", "Malcompliant 10-107 at my 10-20, preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav")
Schema.voices.Add("Combine", "malignant", "Malignant!", "npc/metropolice/vo/malignant.wav")
Schema.voices.Add("Combine", "match on apb", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav")
Schema.voices.Add("Combine", "minor hits", "Minor hits, continuing prosecution!", "npc/metropolice/vo/minorhitscontinuing.wav")
Schema.voices.Add("Combine", "move along", "Move along!", "npc/metropolice/vo/movealong.wav")
Schema.voices.Add("Combine", "move back", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav")
Schema.voices.Add("Combine", "move in", "Move in!", "npc/combine_soldier/vo/movein.wav")
Schema.voices.Add("Combine", "move it", "Move it!", "npc/metropolice/vo/moveit.wav")
Schema.voices.Add("Combine", "move", "Move!", "npc/metropolice/vo/move.wav")
Schema.voices.Add("Combine", "moving to cover", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav")
Schema.voices.Add("Combine", "moving to hardpoint", "Moving to hardpoint!", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("Combine", "necrotics", "Necrotics!", "npc/metropolice/vo/necrotics.wav")
Schema.voices.Add("Combine", "need any help", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("Combine", "needs assistance", "Officer needs assistance, I am 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
Schema.voices.Add("Combine", "needs help", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav")
Schema.voices.Add("Combine", "no 647", "Clear, no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav")
Schema.voices.Add("Combine", "no contact", "No contact!", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("Combine", "no i'm good", "No, I'm good.", "vo/trainyard/ba_noimgood.wav")
Schema.voices.Add("Combine", "no visual on", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav")
Schema.voices.Add("Combine", "nomad", "Nomad.", "npc/combine_soldier/vo/nomad.wav")
Schema.voices.Add("Combine", "noncitizen", "Noncitizen.", "npc/metropolice/vo/noncitizen.wav")
Schema.voices.Add("Combine", "nonpatrol", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("Combine", "nontagged viromes", "Non-tagged viromes here!", "npc/metropolice/vo/non-taggedviromeshere.wav")
Schema.voices.Add("Combine", "nova", "Nova.", "npc/combine_soldier/vo/nova.wav")
Schema.voices.Add("Combine", "now get out", "Now, get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav")
Schema.voices.Add("Combine", "now", "Now.", "vo/trainyard/ba_thatbeer01.wav")
Schema.voices.Add("Combine", "outbreak", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav")
Schema.voices.Add("Combine", "outbreak", "Outbreak!", "npc/metropolice/vo/outbreak.wav")
Schema.voices.Add("Combine", "overwatch", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav")
Schema.voices.Add("Combine", "pacifying", "Pacifying!", "npc/metropolice/vo/pacifying.wav")
Schema.voices.Add("Combine", "pain1", "Ugh!", "npc/metropolice/pain1.wav")
Schema.voices.Add("Combine", "pain2", "Uagh!", "npc/metropolice/pain2.wav")
Schema.voices.Add("Combine", "pain3", "Augh!", "npc/metropolice/pain3.wav")
Schema.voices.Add("Combine", "pain4", "Agh!", "npc/metropolice/pain4.wav")
Schema.voices.Add("Combine", "patrol", "Patrol!", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("Combine", "payback", "Payback.", "npc/combine_soldier/vo/payback.wav")
Schema.voices.Add("Combine", "phantom", "Phantom.", "npc/combine_soldier/vo/phantom.wav")
Schema.voices.Add("Combine", "pickup 647e", "Anyone else pick up a, uh... 647-E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
Schema.voices.Add("Combine", "position at hardpoint", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav")
Schema.voices.Add("Combine", "position to contain", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav")
Schema.voices.Add("Combine", "possible 404", "Possible 404 here!", "npc/metropolice/vo/possible404here.wav")
Schema.voices.Add("Combine", "possible 647e", "Possible 647-E here, request AirWatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav")
Schema.voices.Add("Combine", "possible accomplice", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav")
Schema.voices.Add("Combine", "possible level 3", "Possible level three civil-privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
Schema.voices.Add("Combine", "preparing to judge", "Preparing to judge a 10-107, be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav")
Schema.voices.Add("Combine", "preserve", "Preserve!", "npc/metropolice/vo/preserve.wav")
Schema.voices.Add("Combine", "pressure", "Pressure!", "npc/metropolice/vo/pressure.wav")
Schema.voices.Add("Combine", "priority 1", "Confirm, priority-one sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav")
Schema.voices.Add("Combine", "priority 2", "I have a priority-two anti-citizen here!", "npc/metropolice/vo/priority2anticitizenhere.wav")
Schema.voices.Add("Combine", "production block", "Production-block.", "npc/metropolice/vo/productionblock.wav")
Schema.voices.Add("Combine", "prosecute malcompliant", "Ready to prosecute malcompliant citizen, final warning issued!", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
Schema.voices.Add("Combine", "prosecute", "Prosecute!", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("Combine", "prosecuting", "Prosecuting.", "npc/combine_soldier/vo/prosecuting.wav")
Schema.voices.Add("Combine", "protection complete", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav")
Schema.voices.Add("Combine", "quick", "Quick!", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("Combine", "quicksand", "Quicksand.", "npc/combine_soldier/vo/quicksand.wav")
Schema.voices.Add("Combine", "range", "Range.", "npc/combine_soldier/vo/range.wav")
Schema.voices.Add("Combine", "ranger", "Ranger.", "npc/combine_soldier/vo/ranger.wav")
Schema.voices.Add("Combine", "razor", "Razor.", "npc/combine_soldier/vo/razor.wav")
Schema.voices.Add("Combine", "ready amputate", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav")
Schema.voices.Add("Combine", "ready charges", "Ready charges!", "npc/combine_soldier/vo/readycharges.wav")
Schema.voices.Add("Combine", "ready judge", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav")
Schema.voices.Add("Combine", "ready prosecute", "Ready to prosecute!", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("Combine", "ready weapons", "Ready weapons!", "npc/combine_soldier/vo/readyweapons.wav")
Schema.voices.Add("Combine", "reaper", "Reaper.", "npc/combine_soldier/vo/reaper.wav")
Schema.voices.Add("Combine", "reinforcement teams", "Reinforcement-teams, code three!", "npc/metropolice/vo/reinforcementteamscode3.wav")
Schema.voices.Add("Combine", "report clear", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("Combine", "report in", "CP requests all units, uhh... Location report-in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
Schema.voices.Add("Combine", "report location", "All units, report location suspect!", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("Combine", "report status", "Local CP-teams, report status.", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("Combine", "repurposed", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav")
Schema.voices.Add("Combine", "residential block", "Residential block.", "npc/metropolice/vo/residentialblock.wav")
Schema.voices.Add("Combine", "respond code 3", "All units at location, responding code three!", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("Combine", "responding", "Responding.", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("Combine", "restrict", "Restrict!", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("Combine", "restricted", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav")
Schema.voices.Add("Combine", "restriction zone", "Terminal restriction-zone!", "npc/metropolice/vo/terminalrestrictionzone.wav")
Schema.voices.Add("Combine", "ripcord", "Ripcord!", "npc/combine_soldier/vo/ripcord.wav")
Schema.voices.Add("Combine", "rodger that", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav")
Schema.voices.Add("Combine", "roller", "Roller!", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("Combine", "running", "He's running!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("Combine", "sacrifice code", "All units, sacrifice code one and maintain this CP!", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
Schema.voices.Add("Combine", "savage", "Savage.", "npc/combine_soldier/vo/savage.wav")
Schema.voices.Add("Combine", "scar", "Scar.", "npc/combine_soldier/vo/scar.wav")
Schema.voices.Add("Combine", "search", "Search!", "npc/metropolice/vo/search.wav")
Schema.voices.Add("Combine", "searching for suspect", "Searching for suspect.", "npc/metropolice/vo/searchingforsuspect.wav")
Schema.voices.Add("Combine", "second warning", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav")
Schema.voices.Add("Combine", "sector not sterile", "Confirmed- sector not sterile.", "npc/combine_soldier/vo/confirmsectornotsterile.wav")
Schema.voices.Add("Combine", "sector not secure", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("Combine", "secure advance", "Assault-point secured, advance!", "npc/metropolice/vo/assaultpointsecureadvance.wav")
Schema.voices.Add("Combine", "secure", "Secure.", "npc/combine_soldier/vo/secure.wav")
Schema.voices.Add("Combine", "sentence", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav")
Schema.voices.Add("Combine", "serve", "Serve.", "npc/metropolice/vo/serve.wav")
Schema.voices.Add("Combine", "shadow", "Shadow.", "npc/combine_soldier/vo/shadow.wav")
Schema.voices.Add("Combine", "sharpzone", "Sharpzone.", "npc/combine_soldier/vo/sharpzone.wav")
Schema.voices.Add("Combine", "shit", "Shit!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("Combine", "shots fired", "Shots fired, hostile malignants here!", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
Schema.voices.Add("Combine", "slam", "Slam.", "npc/combine_soldier/vo/slam.wav")
Schema.voices.Add("Combine", "slash", "Slash.", "npc/combine_soldier/vo/slash.wav")
Schema.voices.Add("Combine", "sociocide", "Sociocide.", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("Combine", "sociostable", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav")
Schema.voices.Add("Combine", "spear", "Spear.", "npc/combine_soldier/vo/spear.wav")
Schema.voices.Add("Combine", "stab", "Stab.", "npc/combine_soldier/vo/stab.wav")
Schema.voices.Add("Combine", "standing by", "Standing by.", "npc/combine_soldier/vo/standingby].wav")
Schema.voices.Add("Combine", "star", "Star.", "npc/combine_soldier/vo/star.wav")
Schema.voices.Add("Combine", "stationblock", "Stationblock.", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("Combine", "stay alert", "Stay alert.", "npc/combine_soldier/vo/stayalert.wav")
Schema.voices.Add("Combine", "sterilize", "Sterilize!", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("Combine", "stinger", "Stinger.", "npc/combine_soldier/vo/stinger.wav")
Schema.voices.Add("Combine", "storm", "Storm.", "npc/combine_soldier/vo/storm.wav")
Schema.voices.Add("Combine", "strike", "Striker.", "npc/combine_soldier/vo/striker.wav")
Schema.voices.Add("Combine", "subject 505", "Subject is 505!", "npc/metropolice/vo/subjectis505.wav")
Schema.voices.Add("Combine", "subject high speed", "All units, be advised, subject is now high-speed!", "npc/metropolice/vo/subjectisnowhighspeed.wav")
Schema.voices.Add("Combine", "subject", "Subject!", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("Combine", "sundown", "Sundown.", "npc/combine_soldier/vo/sundown.wav")
Schema.voices.Add("Combine", "suspect incursion", "Disp reports suspect-incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav")
Schema.voices.Add("Combine", "suspect moved to", "Suspect has moved now to...", "npc/metropolice/vo/supsecthasmovednowto.wav")
Schema.voices.Add("Combine", "suspect restricted canals", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
Schema.voices.Add("Combine", "suspend", "Suspend!", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("Combine", "sweeper", "Sweeper.", "npc/combine_soldier/vo/sweeper.wav")
Schema.voices.Add("Combine", "sweeping in", "Sweeping in!", "npc/combine_soldier/vo/sweepingin.wav")
Schema.voices.Add("Combine", "sweeping suspect", "Sweeping for suspect!", "npc/metropolice/vo/sweepingforsuspect.wav")
Schema.voices.Add("Combine", "swift", "Swift.", "npc/combine_soldier/vo/swift.wav")
Schema.voices.Add("Combine", "sword", "Sword.", "npc/combine_soldier/vo/sword.wav")
Schema.voices.Add("Combine", "tag 10-91d", "Tag 10-91d!", "npc/metropolice/vo/tag10-91d.wav")
Schema.voices.Add("Combine", "tag bug", "Tag one bug!", "npc/metropolice/vo/tagonebug.wav")
Schema.voices.Add("Combine", "tag necrotic", "Tag one necrotic!", "npc/metropolice/vo/tagonenecrotic.wav")
Schema.voices.Add("Combine", "tag parasitic", "Tag one parasitic!", "npc/metropolice/vo/tagoneparasitic.wav")
Schema.voices.Add("Combine", "take a look", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav")
Schema.voices.Add("Combine", "take cover", "Take cover!", "npc/metropolice/vo/takecover.wav")
Schema.voices.Add("Combine", "tap", "Tap!", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("Combine", "target", "Target.", "npc/combine_soldier/vo/target.wav")
Schema.voices.Add("Combine", "team advance", "Team in position, advance!", "npc/metropolice/vo/teaminpositionadvance.wav")
Schema.voices.Add("Combine", "team holding", "Stabilization team holding in position.", "npc/combine_soldier/vo/stabilizationteamholding.wav")
Schema.voices.Add("Combine", "there he goes", "There he goes! He's at...", "npc/metropolice/vo/therehegoeshesat.wav")
Schema.voices.Add("Combine", "there he is", "There he is!", "npc/metropolice/vo/thereheis.wav")
Schema.voices.Add("Combine", "tracker", "Tracker.", "npc/combine_soldier/vo/tracker.wav")
Schema.voices.Add("Combine", "transitblock", "Transit-block.", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("Combine", "trouble", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav")
Schema.voices.Add("Combine", "under fire", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav")
Schema.voices.Add("Combine", "uniform", "Uniform.", "npc/combine_soldier/vo/uniform.wav")
Schema.voices.Add("Combine", "union", "Union!", "npc/metropolice/vo/union.wav")
Schema.voices.Add("Combine", "unknown", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav")
Schema.voices.Add("Combine", "up there", "He's up there!", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("Combine", "upi", "UPI.", "npc/metropolice/vo/upi.wav")
Schema.voices.Add("Combine", "utl suspect", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav")
Schema.voices.Add("Combine", "utl", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav")
Schema.voices.Add("Combine", "vacate", "Vacate, citizen!", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("Combine", "vamp", "Vamp.", "npc/combine_soldier/vo/vamp.wav")
Schema.voices.Add("Combine", "verdict", "You want a malcompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
Schema.voices.Add("Combine", "vice", "Vice!", "npc/metropolice/vo/vice.wav")
Schema.voices.Add("Combine", "victor", "Victor!", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("Combine", "viscon", "Viscon.", "npc/combine_soldier/vo/viscon.wav")
Schema.voices.Add("Combine", "visual exogen", "Visual on exogen.", "npc/combine_soldier/vo/visualonexogens.wav")
Schema.voices.Add("Combine", "warning given", "Second warning given!", "npc/metropolice/vo/secondwarning.wav")
Schema.voices.Add("Combine", "wasteriver", "Wasteriver.", "npc/metropolice/vo/wasteriver.wav")
Schema.voices.Add("Combine", "watch it", "Watch it!", "npc/metropolice/vo/watchit.wav")
Schema.voices.Add("Combine", "winder", "Winder.", "npc/combine_soldier/vo/winder.wav")
Schema.voices.Add("Combine", "workforce", "Workforce intake.", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("Combine", "wrap it up", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("Combine", "xray", "XRay!", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("Combine", "yellow", "Yellow!", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("Combine", "you can go", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("Combine", "zone", "Zone!", "npc/metropolice/vo/zone.wav")

Schema.voices.Add("Dispatch", "activity level 1", "You are charged with anti-civil activity level: ONE. Protection-unit prosecution code: DUTY, SWORD, OPERATE.", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "anti-citizen", "Attention, ground-units: Anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav", true)
Schema.voices.Add("Dispatch", "anti-civil evidence", "Protection-team, alert: Evidence of anti-civil activity in this community. Code: ASSEMBLE, CLAMP, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "are charged with", "Individual, you are charged with capital malcompliance. Anti-citizen status, APPROVED.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav", true)
Schema.voices.Add("Dispatch", "assume positions", "Attention, please: All citizens in local residential block, assume your inspection-positions.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav", true)
Schema.voices.Add("Dispatch", "autonomous judgment", "Attention, all ground-protection teams, autonomous judgment is now in effect. Sentencing is now discretionary. Code, AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "citizen relocation", "Citizen notice: Failure to co-operate will result in permanent off-world relocation.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav", true)
Schema.voices.Add("Dispatch", "conspiracy", "Citizen reminder: Inaction is conspiracy. Report counter-behavior to a Civil-Protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav", true)
Schema.voices.Add("Dispatch", "convicted", "Individual, you are convicted of multi-anti-civil violations. Implict citizenship revoked. Status, MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav", true)
Schema.voices.Add("Dispatch", "deducted", "Attention, occupants: Your block is now charged with permissive inactive coersion. Five ration-units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "evasion behavior", "Attention, please, evasion behaviour consistent with malcompliant defendant. Ground protection-team, alert, code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav", true)
Schema.voices.Add("Dispatch", "individual charged with", "Individual, you are charged with socio-endangerment level: ONE. Protection-unit prosecution code, DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "inspection", "Citizen notice, priority identification-check in-progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav", true)
Schema.voices.Add("Dispatch", "judgment waiver", "Attention, all ground-protection teams, judgment waiver now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "miscount detected", "Attention, residents: Miscount detected in your block. Co-operation with your Civil Protection team permits full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav", true)
Schema.voices.Add("Dispatch", "mission failure", "Attention, ground-units: Mission-failure will result in permanent off-world assignment. Code-reminder: SACRIFICE, COAGULATE, CLAMP.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav", true)
Schema.voices.Add("Dispatch", "overwatch acknowledges", "Overwatch acknowledges critical exogen-breach. AirWatch augmentation-force dispatched and inbound. Hold for re-enforcement.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav", true)
Schema.voices.Add("Dispatch", "potential infection", "Attention, residents: This blocks contains potential civil infection. INFORM, CO-OPERATE, ASSEMBLE.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav", true)
Schema.voices.Add("Dispatch", "receive your verdict", "Individual, you are now charged with socio-endangerment level: FIVE. Cease evasion immediately, recieve your verdict.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav", true)
Schema.voices.Add("Dispatch", "status evasion", "Attention, protection-team, status evasion in progress in this community. RESPOND, ISOLATE, INQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "unidentified", "Attention, please: Unidentified person of interest, confirm your civil status with local protection-team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "unrest procedure", "Attention, community: Unrest procedure code is now in effect. INNOCULATE, SHIELD, PACIFY. Code: PRESSURE, SWORD, STERILIZE.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav", true)
Schema.voices.Add("Dispatch", "unrest structure", "Alert, community ground-protection units, local unrest structure detected. ASSEMBLE, ADMINISTER, PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav", true)

    Schema.voices.AddClass("TGU", function(client)
        return client:IsTGU()
    end)
    Schema.voices.AddClass("Combine", function(client)
        return client:IsCombine()
    end)
    Schema.voices.AddClass("Dispatch", function(client)
        return client:IsDispatch()
    end)
